site_name: python-tool-notes
site_url: https://lid23.github.io/python-tool-notes/
site_author: Noodles
site_description: Python工具方法使用总结

# Repository
repo_name: python-tool-notes
repo_url: https://github.com/Lid23/python-tool-notes
edit_uri: https://github.com/Lid23/python-tool-notes/tree/main/docs/

# Copyright
copyright: Copyright &copy; 2023 Noodles



# Configuration
theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    logo: material/library
    repo: fontawesome/brands/git
    edit: material/file-edit-outline


plugins:
  - search

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/tablesort.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic

nav:
  - 首页: index.md
  - 1.基础处理:
    - 1.1.变量: 1-基础处理/1.1.变量.md
    - 1.2.基本数据类型: 1-基础处理/1.2.基本数据类型.md
    - 1.3.字符串和正则: 1-基础处理/1.md
    - 1.4.运算符和表达式: 1-基础处理/1.md
    - 1.5.流程控制: 1-基础处理/1.md
    - 1.6.函数和模块: 1-基础处理/1.md
    - 1.7.异常处理: 1-基础处理/1.md
    - 1.8.日期和时间: 1-基础处理/1.md
  - 2.集合处理:
    - 2.1.序列: 2-集合处理/1.md
    - 2.2.列表: 2-集合处理/1.md
    - 2.3.元组: 2-集合处理/1.md
    - 2.4.集合: 2-集合处理/1.md
    - 2.5.字典: 2-集合处理/1.md
  - 3.面向对象:
    - 3.1 类: 3-面向对象/1.md
    - 3.2 继承: 3-面向对象/1.md
  - 4.进程和线程:
    - 4.1 进程: 4-进程和线程/1.md
    - 4.2 线程: 4-进程和线程/1.md
  - 5.文件处理:
    - 5.1 基本文件目录: 5-文件处理/1.md
    - 5.2 Excel文件: 5-文件处理/1.md
    - 5.3 Json文件: 5-文件处理/1.md
    - 5.4 pdf文件: 5-文件处理/1.md
    - 5.5 csv文件: 5-文件处理/1.md
    - 5.6 xml文件: 5-文件处理/1.md
  - 6.数据库:
    - 6.1 Oracle: 6-数据库/1.md
    - 6.2 Mysql: 6-数据库/1.md
    - 6.3 Redis: 6-数据库/1.md
    - 6.4 Mongo: 6-数据库/1.md
  - 7.网络编程:
    - 7.1 TCP编程: 7-网络编程/1.md
    - 7.2 UDP编程: 7-网络编程/1.md
  - 8.Web编程:
    - 8.1 Http: 8-Web编程/1.md
    - 8.2 Wsgi: 8-Web编程/1.md
    - 8.3 Flask框架: 8/1.md
  - 9.性能分析:
    - 9.1 性能分析: 9-性能分析/1.md
  - 10.问题总结:
    - 10.1 问题总结: 10-问题总结/1.md

