site_name: python-tool-notes
site_url: https://lid23.github.io/python-tool-notes/
site_author: Noodles
site_description: Python工具方法使用总结

# Repository
repo_name: python-tool-notes
repo_url: https://github.com/Lid23/python-tool-notes
edit_uri: https://github.com/Lid23/python-tool-notes/tree/main/docs/

# Copyright
copyright: Copyright &copy; 2023 Noodles



# Configuration
theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    logo: material/library
    repo: fontawesome/brands/git
    edit: material/file-edit-outline


plugins:
  - search

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/tablesort.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic

nav:
  - 首页: index.md
  - 1.Java基础:
    - 1.1.Java基础: 1/1.1.md
    - 1.2.OOP: 1/1.2.md
  - 2.Java集合:
    - 2.1.List: 2/2.1.md
    - 2.2.Map: 2/2.2.md
  - 3.扩展:
    - 3.1 math: 3/math.md
    - 3.2 images: 3/images.md
    - 3.3 formatting: 3/formatting.md
    - 3.4 code blocks: 3/code-blocks.md
    - 3.5 content tabs: 3/content-tabs.md
    - 3.6 data tables: 3/data-tables.md
    - 3.7 diagrams: 3/diagrams.md
    - 3.8 footnotes: 3/footnotes.md